lab6/urls.py
from django.urls import path, include
from . import views

app_name = 'lab6'

urlpatterns = [
    path('', views.status, name="status"),
]

lab7/urls.py
from django.urls import path, include
from . import views

app_name = 'lab7'

urlpatterns = [
    path('', views.index),
]

lab8/urls.py
from django.urls import path, include
from . import views

app_name = 'lab8'

urlpatterns = [
    path('', views.index),
]

lab9/urls.py
from django.urls import path, include
from . import views

app_name = 'lab9'

urlpatterns = [
    path('', views.index, name="index"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
]

pepewe/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lab6.urls'), name='lab6'),
    path('lab7/', include('lab7.urls'), name='lab7'),
    path('lab8/', include('lab8.urls'), name='lab8'),
    path('lab9/', include('lab9.urls'), name='lab9'),
]

lab6/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
    status_message = models.CharField(max_length=300)
    waktu_pengisian = models.DateTimeField(default=timezone.now)

lab7/models.py
from django.db import models

# Create your models here.

lab8/models.py
from django.db import models

# Create your models here.

lab9/models.py
from django.db import models

# Create your models here.

lab6/forms.py
from . import models
from django import forms

class StatusForm(forms.ModelForm):
        status_message = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "input",
                "id" : "status-input",
                "required" : True,
                "placeholder":"What's your status",
                "max_length": 300,
                "autocomplete": 'off',
                }))

        class Meta:
                model = models.Status
                fields = ["status_message"]

lab6/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm
from .models import Status

def status(request):
    form = StatusForm()
    statuses = Status.objects.all()
    if request.method=="POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lab6:status')      
    return render(request, 'index.html', {'form':form, 'statuses':statuses})

lab7/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'lab7.html')

lab8/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'lab8.html')

lab9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as login_auth, logout as logout_auth
from lab6.models import Status

def index(request):
    user = request.user
    if user.is_authenticated:
        return render(request, 'hello.html')        
    else:
        return render(request, 'lab9.html')

def login(request):
    user = request.user
    login_form = AuthenticationForm()
    
    if user.is_authenticated:
        return redirect('lab9:index')

    if request.method == "POST":
        login_form = AuthenticationForm(data = request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login_auth(request, user)
            return redirect('lab9:index')
    return render(request, 'login.html', {'form':login_form})

def logout(request):
    if request.method == 'POST':
        logout_auth(request)
    return redirect('lab9:index')

lab6/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>PPW LEONARDO 6</title>
</head>
<body>
    <div>
        <h1 id="title">Share your Status Right now</h1>
    </div>
    <div class="dflex-center">
        <form method="POST">
            {% csrf_token %}
            {{form.status_message}}
            <input type="submit" class="button" value="Share">
        </form>
    </div>
    <div class="status dflex-center" name="statuses">
        {% for status in statuses %}
            <div class="item">
                <h3>{{ status.status_message }}</h3>
                <p>{{ status.waktu_pengisian }}</p>
            </div>
        {% endfor %}
    </div>
</body>
</html>

lab7/templates/lab7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style7.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/script7.js' %}"></script>
    <title>PPW LEONARDO 7</title>
</head>
<body style="background-color: rgb(255, 255, 255);">
    <div class="custom-control custom-switch" id="change">
        <input type="checkbox" class="custom-control-input" id="customSwitch1" onchange="change()">
        <label class="custom-control-label" for="customSwitch1" id="toggle">Change Theme</label>
    </div>
    <div>
        <h1>Hi I'm Leonardo</h1>
        <p>Here is what i'm doing so far</p>
    </div>
    <div id="accordion">
        <h3>Activity</h3>
        <div>
            <p>Eat</p>
            <p>Sleep</p>
            <p>Code</p>
        </div>
        <h3>Experience</h3>
        <div>
            <p>- PTI 2019</p>
            <p>- Staff Equipment Betis 2019</p>
            <p>- Mentoria Indonesia</p>
        </div>
        <h3>Achievement</h3>
        <div>
            <p>- 3rd Winner of CITD Pekan Ristek 2019</p>
        </div>
    </div>
</body>
</html>

lab8/templates/lab8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style8.css' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>PPW LEONARDO 8</title>
</head>
<body>
    <div class="container">
        <h1 class="text-align-center">Search Your Books Here</h1>
        <div class="d-flex justify-content-center">
            <div class="form-inline active-grey-4 search">
                <input class="form-control form-control-sm mr-3 w-100 text-align-center" id="search" type="text" placeholder="Search" aria-label="Search" autocomplete="off">
            </div>
        </div>
        <div id="result" class="p-1 d-flex flex-wrap"></div>
        <div class="">
            <nav aria-label="...">
                <ul class="pagination justify-content-center">
                  <li class="page-item disabled" id="prev">
                    <p class="page-link"  tabindex="-1">Previous</p>
                  </li>
                  <li class="page-item active">
                    <p class="page-link" id="current">1 <span class="sr-only">(current)</span></p>
                  </li>
                  <li class="page-item" id="next">
                    <p class="page-link" >Next</p>
                  </li>
                </ul>
              </nav>
        </div>
    </div>
</body>
<script src="{% static 'js/script8.js' %}"></script>
</html>

lab9/templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LOGIN</title>
</head>
<body>
    hello {{ user.username }}
    <form action="{% url 'lab9:logout' %}" method="POST" class="test mid" style="color:white">
            {% csrf_token %}
            <div class="unknown test">
                <button type="submit" class="formbutton">Logout</button>
            </div>
    </form>
</body>
</html>

lab9/templates/lab9.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style9.css' %}">
    <title>PPW LEONARDO 9</title>
</head>
<body>
    <div>
        <a href="login">
            <button>Login</button>
        </a>
    </div>
</body>
</html>

lab9/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
        <div class='BlockContent test'>
                <div class="form">
                    <center><h2>LOGIN</h2></center>
                    <form action="{% url 'lab9:login' %}" method="POST" class="test mid" style="color:white">
                        {% csrf_token %}
                        <div class="unknown"><p>Username</p>{{ form.username }}</div>
                        <div class="unknown"><p>Password</p>{{ form.password }}</div>
                        <div class="unknown test">
                            <button type="submit" class="formbutton">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        
</body>
</html>